---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: alfatemplates.controllers.illallangi.enterprises
spec:
  group: controllers.illallangi.enterprises
  names:
    kind: AlfaTemplate
    plural: alfatemplates
    shortNames:
    - alfatemplate
    - at
    singular: alfatemplate
  scope: Cluster
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              scope:
                pattern: ^(Cluster|Namespace|Domain|Object)$
                type: string
                default: Object
              kinds:
                type: object
                properties:
                  parent:
                    type: object
                    properties:
                      kind:
                        type: string
                    required:
                    - kind
                  child:
                    type: object
                    properties:
                      kind:
                        type: string
                    required:
                    - kind
                  monitored:
                    default: []
                    type: array
                    items:
                      type: object
                      properties:
                        kind:
                          type: string
                      required:
                      - kind
                required:
                - parent
                - child
              template:
                type: string
              ownerReferences:
                type: boolean
                default: true
              component:
                type: string
              update:
                default: true
                type: boolean
              labels:
                type: object
                default:
                  name: app.kubernetes.io/name
                  partOf: app.kubernetes.io/part-of
                  instance: app.kubernetes.io/instance
                  domainName: app.kubernetes.io/domain-name
                  component: app.kubernetes.io/component
                  managedBy: app.kubernetes.io/managed-by
                properties:
                  name:
                    type: string
                    default: app.kubernetes.io/name
                  partOf:
                    type: string
                    default: app.kubernetes.io/part-of
                  instance:
                    type: string
                    default: app.kubernetes.io/instance
                  domainName:
                    type: string
                    default: app.kubernetes.io/domain-name
                  component:
                    type: string
                    default: app.kubernetes.io/component
                  managedBy:
                    type: string
                    default: app.kubernetes.io/managed-by
            required:
            - kinds
            - template
            type: object
        required:
        - spec
        type: object
    served: true
    storage: true

---
apiVersion: v1
kind: Namespace
metadata:
  name: alfa-system

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: alfaoperatr
  namespace: alfa-system

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: alfaoperatr
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: alfaoperatr
  namespace: alfa-system

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alfaoperatr
  namespace: alfa-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: alfaoperatr
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: alfaoperatr
    spec:
      containers:
      - name: operator
        image: docker.io/illallangi/alfaoperatr:latest
      - name: proxy
        image: docker.io/bitnami/kubectl:1.18.0
        args:
        - proxy
      serviceAccountName: alfaoperatr
